name: flutter_amplitude
description: Flutter pluging for Amplitude SDK
version: 0.0.3
author: Miguel Catalan<miguel.catalan@eval.ly>
homepage: https://github.com/Evally/flutter_amplitude

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ly.eval.flutteramplitude
    pluginClass: FlutterAmplitudePlugin
